presentation/Store.web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Store.web.Models;

namespace Store.web.Controllers
{
    public class BookController : Controller
    {
        private readonly BookService bookService;

        public BookController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var model = await bookService.GetByIdAsync(id);
            return View(model);
        }

        public IActionResult InputNewBook()
        {
            return View();
        }

        public async Task<IActionResult> AddBookResult(string isbn,
                                         string author,
                                         string title,
                                         string description,
                                         string price,
                                         string image)
        {
            int bookId;
            try
            {
                bookId = await bookService.AddNewBookAsync(isbn, author, title, description, Convert.ToDecimal(price), image);
            }
            catch { return View("Error", new ErrorViewModel()); }
            return View(await bookService.GetByIdAsync(bookId));
        }

        public async Task<IActionResult> RemoveBookFromDB(int bookId)
        {
            await bookService.RemoveBookAsync(bookId);
            return RedirectToAction("Index", "Home");
        }
    }
}

presentation/Store.web/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Store.web.Controllers
{
    public class CatalogController : Controller
    {

		private readonly BookService bookService;

		public CatalogController(BookService bookService)
		{
			this.bookService = bookService;
		}

		public IActionResult Index()
        {
            return View();
        }

		public async Task<IActionResult> AllBooks()
		{
			var books = await bookService.GetAllAsync();
			return View(books);
		}
	}
}

presentation/Store.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Store.web.Models;
using System.Text.RegularExpressions;
using Store.Messages;
using Store.Contractors;
using Store.web.Contractors;
using Store.web.App;
using System;

namespace Store.web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService orderService;
        private readonly IEnumerable<IDeliveryService> deliveryServices;
        private readonly IEnumerable<IPaymentService> paymentServices;
        private readonly IEnumerable<IWebContractorService> webContractorServices;

        public OrderController(OrderService orderService,
                               IEnumerable<IDeliveryService> deliveryServices,
                               IEnumerable<IPaymentService> paymentServices,
                               IEnumerable<IWebContractorService> webContractorServices)
        {
            this.orderService = orderService;
            this.deliveryServices = deliveryServices;
            this.paymentServices = paymentServices;
            this.webContractorServices = webContractorServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var (hasValue, model) = await orderService.TryGetModelAsync();
            if (hasValue)
                return View(model);

            return View("Empty");
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(int bookId, int count = 1)
        {
            await orderService.AddBookAsync(bookId, count);
            return RedirectToAction("Index", "Book", new { id = bookId });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItem(int bookId)
        {
            var model = await orderService.RemoveBookAsync(bookId);
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateItem(int bookId, int count)
        {
            var model = await orderService.UpdateBookAsync(bookId, count);
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> SendConfirmation(string cellPhone)
        {
            var model = await orderService.SendConfirmationAsync(cellPhone);
            return View("Confirmation", model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmCellPhone(string cellPhone, int confirmationCode)
        {
            var model = await orderService.ConfirmCellPhoneAsync(cellPhone, confirmationCode);
            if (model.Errors.Count > 0)
                return View("Confirmation", model);
            var deliveryMethods = deliveryServices.ToDictionary(service => service.Name,
                                                                service => service.Title);
            return View("DeliveryMethod", deliveryMethods);
        }

        [HttpPost]
        public async Task<IActionResult> StartDelivery(string serviceName)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);
            var order = await orderService.GetOrderAsync();
            var form = deliveryService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("DeliveryStep", form);

            var returnUri = GetReturnUri(nameof(NextDelivery));
            var redirectUri = await webContractorService.StartSessionAsync(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        [HttpPost]
        public async Task<IActionResult> NextDelivery(string serviceName, int step, Dictionary<string, string> values)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);

            var form = deliveryService.NextForm(step, values);
            if (!form.IsFinal)
                return View("DeliveryStep", form);

            var delivery = deliveryService.GetDelivery(form);
            await orderService.SetDeliveryAsync(delivery);

            var paymentMethods = paymentServices.ToDictionary(service => service.Name,
                                                              service => service.Title);

            return View("PaymentMethod", paymentMethods);
        }

        private Uri GetReturnUri(string action)
        {
            var builder = new UriBuilder(Request.Scheme, Request.Host.Host)
            {
                Path = Url.Action(action),
                Query = null,
            };

            if (Request.Host.Port != null)
                builder.Port = Request.Host.Port.Value;

            return builder.Uri;
        }

        [HttpPost]
        public async Task<IActionResult> StartPayment(string serviceName)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);
            var order = await orderService.GetOrderAsync();
            var form = paymentService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("PaymentStep", form);

            var returnUri = GetReturnUri(nameof(NextPayment));
            var redirectUri = await webContractorService.StartSessionAsync(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        [HttpPost]
        public async Task<IActionResult> NextPayment(string serviceName, int step, Dictionary<string, string> values)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);

            var form = paymentService.NextForm(step, values);
            if (!form.IsFinal)
                return View("PaymentStep", form);

            var payment = paymentService.GetPayment(form);
            var model = await orderService.SetPaymentAsync(payment);

            return View("Finish", model);
        }
    }
}

presentation/Store.web/Views/Catalog/AllBooks.cshtml
@model IReadOnlyCollection<BookModel>

@{
	ViewData["Title"] = "Все книги в базе данных";
}
<link rel="stylesheet" href="~/css/catalog2.css">

<p class="text-center">Всего книг в базе данных: @Model.Count</p>
@if (Model == null || Model.Count == 0)
{
	<p>По вашему запросу ничего не найдено</p>
}
else
{
	<ul class="listBooks">
		@foreach (var book in Model)
		{
			
			@if (!book.Image.StartsWith("http")) book.Image = "/" + book.Image;
			<li class="li-container">
				<a href="@Url.Action("Index", "Book", new{id = book.Id})" class="book">
					<div class="cover">
						<img src="@book.Image" alt="@book.Image">
					</div>
					<div class="info">
						<div class="title bg-warning"><strong>@book.Title</strong></div>
						<div class="author"><strong>@book.Author</strong></div>
						<div class="description">@book.Description</div>
					</div>
					<p>ID(@book.Id)</p>
				</a>
				<div class="price">
					<form action="@Url.Action(nameof(OrderController.AddItem), "Order")" method="post">
						<input type="hidden" name="bookId" value="@book.Id" />
						<button class="btn btn-outline-success" type="submit">@Math.Round(book.Price, 2)₽</button>
					</form>
				</div>
			</li>
		}
	</ul>
}
@* <ul class="listBooks">
	<li class="li-container">
		<a href="" class="book">
			<div class="cover">
				<img src="/images/10.png" alt="book">
			</div>
			<div class="info">
				<div class="title bg-warning"><strong>Title</strong></div>
				<div class="author">Author</div>
				<div class="description">Тут длиииии иииииииии ииииииииииииииии ииииииииииииииии ииииииии ииииииии нное описание............... .................И тут тоже</div>
			</div>
			<div class="price">100$</div>
		</a>
	</li>
	<li class="li-container">
		<a href="" class="book">
			<div class="cover">
				<img src="/images/10.png" alt="book">
			</div>
			<div class="info">
				<div class="txt bg-warning"><strong>Title 2</strong></div>
				<div class="txt">Author</div>
				<div class="txt">Тут длиииии иииииииии ииииииииииииииии ииииииииииииииии ииииииии ииииииии нное описание............... .................И тут тоже</div>
			</div>
			<div class="price">99.99$</div>
		</a>
	</li>

</ul> *@

presentation/Store.web/Views/Catalog/Index.cshtml
@{
    ViewData["Title"] = "Каталог";
}
<link rel="stylesheet" href="~/css/catalog.css">

<p class="text-center">ТЕСТОВЫЙ КАТАЛОГ</p>

<ul class="products clearfix">
	<li class="product-wrapper">
		<a href="@Url.Action("AllBooks","Catalog")" class="product">
			<div class="product-photo">
				<img src="~/images/back.jpeg" alt="all">
			</div>
			<p class="text-center">Все книги</p>
		</a>
	</li>
	<li class="product-wrapper">
		<a href="" class="product">
			<div class="product-photo">
				<img src="images/books.jpeg" alt="images/books.jpeg">
			</div>
			<p class="text-center">Раздел</p>
		</a>
	</li>
	<li class="product-wrapper">
		<a href="" class="product">
			<div class="product-photo">
				<img src="images/books.jpeg" alt="images/books.jpeg">
			</div>
			<p class="text-center">Раздел</p>
		</a>
	</li>
	<li class="product-wrapper">
		<a href="" class="product">
			<div class="product-photo">
				<img src="images/books.jpeg" alt="images/books.jpeg">
			</div>
			<p class="text-center">Раздел</p>
		</a>
	</li>
	<li class="product-wrapper">
		<a href="" class="product">
			<div class="product-photo">
				<img src="images/books.jpeg" alt="images/books.jpeg">
			</div>
			<p class="text-center">Раздел</p>
		</a>
	</li>
	<li class="product-wrapper">
		<a href="" class="product">
			<div class="product-photo">
				<img src="images/books.jpeg" alt="images/books.jpeg">
			</div>
			<p class="text-center">Раздел</p>
		</a>
	</li>
	
</ul>